{
 "title": "SRE-SHIFT-cAdvisor",
 "tags": [
  "main",
  "okd",
  "MSS"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(kube_pod_info, cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "POD",
    "query": {
     "query": "label_values(container_memory_working_set_bytes{namespace=~\"$namespace\", container!=\"POD\",container!=\"deployment\",container!=\"copy-sitemap\",cluster=\"$environment\"}, container_label_io_kubernetes_pod_name)"
    }
   },
   {
    "name": "container_name",
    "label": "container_name",
    "query": {
     "query": "label_values(container_memory_working_set_bytes{namespace=~\"$namespace\", container!=\"POD\",container!=\"deployment\",container!=\"copy-sitemap\", pod_name=\"$pod\"}, container)"
    }
   },
   { "name": "alertname", "label": "alertname", "query": { "query": "" } },
   {
    "name": "pod_name",
    "label": "pod_name",
    "query": {
     "query": "label_values(container_memory_working_set_bytes{container_name=~\"$container_name\"}, container_label_io_kubernetes_pod_name)"
    }
   },
   {
    "name": "app",
    "label": "app",
    "query": {
     "query": "label_values(container_memory_working_set_bytes{namespace=~\"$namespace\", container!=\"POD\",container!=\"deployment\",container!=\"copy-sitemap\"}, container)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(kube_pod_info, cluster)"
   }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilisation (from requests)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster=\"$cluster\", namespace=\"$namespace\",pod=~\"^$app-.+\"}) / sum(kube_pod_container_resource_requests_cpu_cores{cluster=\"$cluster\", namespace=\"$namespace\",pod=~\"^$app-.+\"})"
    }
   ]
  },
  {
   "title": "Memory Utilization (from requests)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\",container!=\"\", image!=\"\",pod=~\"^$app-.+\"}) / sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\",pod=~\"^$app-.+\"})"
    }
   ]
  },
  {
   "title": "avg \"closewait\" connections",
   "type": "singlestat",
   "description": "\"Amount of connections that are not being used and wait to be released by application. Usually it shows incorrect connections management in the application.\"",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "max(container_network_tcp_usage_total{cluster=~\"$environment\", container_label_io_kubernetes_pod_name=~\"$app-.+\", container_label_io_kubernetes_pod_name!~\".+-.+-deploy\", tcp_state=\"closewait\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Alerts Fired In Prometheus",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 7, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "ALERTS{pod=~\"^$app-\\\\d+-\\\\w{5}$\", namespace=\"$namespace\", cluster=\"$environment\"}"
    }
   ]
  },
  {
   "title": "Instances of $app on namespace: $namespace",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(count(container_memory_usage_bytes{container_label_io_kubernetes_pod_name=~\"^$app-.+\", namespace=\"$namespace\"}) by (container_label_io_kubernetes_pod_name))",
     "legendFormat": "$app"
    }
   ]
  },
  { "title": "resource usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU Usage by $app on namespace: $namespace",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster=\"$cluster\", namespace=\"$namespace\", container=~\"^$app\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "scalar(kube_resourcequota{cluster=\"$cluster\", namespace=\"$namespace\", type=\"hard\",resource=\"requests.cpu\"})",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "scalar(kube_resourcequota{cluster=\"$cluster\", namespace=\"$namespace\", type=\"hard\",resource=\"limits.cpu\"})",
     "legendFormat": "quota - limits"
    }
   ]
  },
  {
   "title": "Memory Usage (w/o cache) by $app on namespace: $namespace",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", container!=\"\", image!=\"\", container=~\"^$app\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "scalar(kube_resourcequota{cluster=\"$cluster\", namespace=\"$namespace\", type=\"hard\",resource=\"requests.memory\"})",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "scalar(kube_resourcequota{cluster=\"$cluster\", namespace=\"$namespace\", type=\"hard\",resource=\"limits.memory\"})",
     "legendFormat": "quota - limits"
    }
   ]
  },
  {
   "title": "pod OOMkilled\\Error happened in app $app",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{cluster=\"$environment\", reason=\"OOMKilled\", namespace=\"$namespace\", container=~\"^$app\"} == 1 and ignoring(reason) kube_pod_container_status_restarts_total{namespace=\"$namespace\", container=~\"^$app\"} -  kube_pod_container_status_restarts_total{namespace=\"$namespace\", container=\"$app\"} offset 1m > 0",
     "legendFormat": "{{ pod }}:  terminated reason: {{ reason }}"
    },
    {
     "expr": "kube_pod_container_status_last_terminated_reason{cluster=\"$environment\", reason=\"Error\", namespace=\"$namespace\", container=\"$app\"} == 1 and ignoring(reason) kube_pod_container_status_restarts_total{namespace=\"$namespace\", container=~\"^$app\"} -  kube_pod_container_status_restarts_total{namespace=\"$namespace\", container=~\"^$app\"} offset 1m > 0",
     "legendFormat": "{{ pod }}:  terminated reason: {{ reason }}"
    }
   ]
  },
  {
   "title": "TCP_STATE  Production-1",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "container_network_tcp_usage_total{container_label_io_kubernetes_pod_name=~\"^$app.+\"}",
     "legendFormat": "{{ instance }}: {{ tcp_state }}: {{ container_label_io_kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "SUM TCP_STATE  $app",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(container_network_tcp_usage_total{container_label_io_kubernetes_pod_name=~\"^$app.+\"}) by (tcp_state)",
     "legendFormat": "{{ tcp_state }}"
    }
   ]
  },
  {
   "title": "Incoming/Outgoing  Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg(rate(container_network_receive_bytes_total{pod=~\"^$app-.+\", namespace=~\"$namespace\",cluster=\"$environment\", pod_name!~\".+-.+-deploy\"}[2m])) by (pod)",
     "legendFormat": "Incoming {{ pod }}"
    },
    {
     "expr": "avg(rate(container_network_transmit_bytes_total{pod=~\"^$app-.+\", namespace=~\"$namespace\",cluster=\"$environment\", pod_name!~\".+-.+-deploy\"}[2m])) by (pod)",
     "legendFormat": "Outgoing {{ pod }}"
    }
   ]
  },
  { "title": "from requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", pod=~\"^$app-.+\", container!=\"POD\", cluster=\"$cluster\"}) by (container)",
     "legendFormat": "{{ container }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"^$app-.+\"})\n",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits_cpu_cores{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"^$app-.+\"})\n",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"^$app-.+\", container!=\"POD\", container!=\"\", image!=\"\"}) by (container)",
     "legendFormat": "{{ container }}"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests_memory_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"^$app-.+\"})\n",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits_memory_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"^$app-.+\"})\n",
     "legendFormat": "limits"
    }
   ]
  }
 ]
}