{
 "title": "Kafka Streams Dashboard",
 "description": "Dashboard for a Kafka Streams application using Prometheus JMX-Exporter running in Kubernetes",
 "tags": [
  "Kafka Streams",
  "Prometheus",
  "Kubernetes",
  "Streams",
  "Kafka"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "App",
    "query": {
     "query": "label_values(kafka_streams_kafka_metrics_count_count,app)"
    }
   },
   {
    "name": "Instance",
    "query": {
     "query": "label_values(kafka_streams_kafka_metrics_count_count{app=~\"${App:pipe}\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Node Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Running Instances",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{deployment=~\"$App\"}"
    }
   ]
  },
  {
   "title": "Currently Running Tasks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_streams_stream_thread_metrics_task_created_total{app=~\"$App\",instance=~\"${Instance:pipe}\"}) - sum(kafka_streams_stream_thread_metrics_task_closed_total{app=~\"$App\",instance=~\"${Instance:pipe}\"})",
     "legendFormat": "Running Tasks"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "kafka_streams_kafka_metrics_count_count{app=~\"$App\",instance=~\"${Instance:pipe}\"}",
     "legendFormat": "{{app}}@{{instance}}"
    },
    {
     "expr": "java_lang_Runtime_Uptime{app=~\"$App\",instance=~\"${Instance:pipe}\"} / 1000",
     "legendFormat": "{{app}}@{{instance}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_admin_client_admin_client_metrics_outgoing_byte_total{app=~\"${App:pipe}.*\",instance=~\"${Instance:pipe}\"})",
     "legendFormat": "Outgoing Network"
    },
    {
     "expr": "sum(kafka_admin_client_admin_client_metrics_incoming_byte_total{app=~\"${App:pipe}.*\",instance=~\"${Instance:pipe}\"})",
     "legendFormat": "Incoming Network"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(java_lang_MemoryPool_Usage_used{app=~\"$App\",instance=~\"${Instance:pipe}\"}) / sum(java_lang_OperatingSystem_TotalPhysicalMemorySize{app=~\"$App\",instance=~\"${Instance:pipe}\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (app,instance) (java_lang_MemoryPool_Usage_used{app=~\"$App\",instance=~\"${Instance:pipe}\"})",
     "legendFormat": "{{app}}@{{instance}}"
    }
   ]
  },
  {
   "title": "Average CPU Load of all Nodes",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(java_lang_OperatingSystem_ProcessCpuLoad{app=~\"$App\",instance=~\"${Instance:pipe}\"})"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_ProcessCpuLoad{app=~\"$App\",instance=~\"${Instance:pipe}\"}",
     "legendFormat": "{{app}}@{{instance}}"
    }
   ]
  },
  {
   "title": "Streams Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_streams_stream_thread_metrics_process_total{app=~\"$App\",instance=~\"${Instance:pipe}\"})",
     "legendFormat": "Processed Records"
    },
    {
     "expr": "sum(kafka_streams_stream_thread_metrics_poll_total{app=~\"$App\",instance=~\"${Instance:pipe}\"})",
     "legendFormat": "Polls"
    },
    {
     "expr": "sum(kafka_streams_stream_thread_metrics_commit_total{app=~\"$App\",instance=~\"${Instance:pipe}\"})",
     "legendFormat": "Commits"
    },
    {
     "expr": "sum(kafka_streams_stream_thread_metrics_task_created_total{app=~\"$App\",instance=~\"${Instance:pipe}\"})",
     "legendFormat": "Created Tasks"
    }
   ]
  },
  {
   "title": "Record E2E Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(kafka_streams_stream_processor_node_metrics_record_e2e_latency_max{app=~\"$App\",instance=~\"${Instance:pipe}\"})",
     "legendFormat": "Max Record E2E Latency"
    },
    {
     "expr": "min(kafka_streams_stream_processor_node_metrics_record_e2e_latency_min{app=~\"$App\",instance=~\"${Instance:pipe}\"})",
     "legendFormat": "Min Record E2E Latency"
    }
   ]
  },
  {
   "title": "Poll Records",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(kafka_streams_stream_thread_metrics_poll_records_max{app=~\"$App\",instance=~\"${Instance:pipe}\"})",
     "legendFormat": "Max Poll"
    },
    {
     "expr": "avg(kafka_streams_stream_thread_metrics_poll_records_avg{app=~\"$App\",instance=~\"${Instance:pipe}\"})",
     "legendFormat": "Avg Poll"
    }
   ]
  },
  {
   "title": "Process Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(kafka_streams_stream_thread_metrics_process_latency_max{app=~\"$App\",instance=~\"${Instance:pipe}\"})",
     "legendFormat": "Max Process Latency"
    },
    {
     "expr": "avg(kafka_streams_stream_thread_metrics_process_latency_avg{app=~\"$App\",instance=~\"${Instance:pipe}\"})",
     "legendFormat": "Avg Process Latency"
    }
   ]
  },
  {
   "title": "Process Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_streams_stream_thread_metrics_process_rate{app=~\"$App\",instance=~\"${Instance:pipe}\"})",
     "legendFormat": "Thread Process Rate"
    }
   ]
  },
  {
   "title": "Poll Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(kafka_streams_stream_thread_metrics_poll_latency_max{app=~\"$App\",instance=~\"${Instance:pipe}\"})",
     "legendFormat": "Max Thread Poll Latency"
    },
    {
     "expr": "avg(kafka_streams_stream_thread_metrics_poll_latency_avg{app=~\"$App\",instance=~\"${Instance:pipe}\"})",
     "legendFormat": "Avg Thread Poll Latency"
    }
   ]
  },
  {
   "title": "Poll Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_streams_stream_thread_metrics_poll_rate{app=~\"$App\",instance=~\"${Instance:pipe}\"})",
     "legendFormat": "Thread Poll Rate"
    }
   ]
  },
  {
   "title": "Commit Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(kafka_streams_stream_thread_metrics_commit_latency_max{app=~\"$App\",instance=~\"${Instance:pipe}\"})",
     "legendFormat": "Max Thread Commit Latency"
    },
    {
     "expr": "avg(kafka_streams_stream_thread_metrics_commit_latency_avg{app=~\"$App\",instance=~\"${Instance:pipe}\"})",
     "legendFormat": "Avg Thread Commit Latency"
    }
   ]
  },
  {
   "title": "Commit Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_streams_stream_thread_metrics_commit_rate{app=~\"$App\",instance=~\"${Instance:pipe}\"})",
     "legendFormat": "Thread Commit Rate"
    }
   ]
  }
 ]
}