{
 "title": "MongoDB Connector",
 "description": "Monitoring Dashboard for Debezium MongoDB connector",
 "tags": [ "debezium" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "name",
    "label": "MongoDB Node",
    "query": {
     "query": "debezium_metrics_TotalNumberOfEventsSeen{plugin=\"mongodb\"}"
    }
   },
   {
    "name": "instance",
    "label": "Connector Node",
    "query": {
     "query": "debezium_metrics_TotalNumberOfEventsSeen{plugin=\"mongodb\"}"
    }
   },
   {
    "name": "context",
    "label": "context",
    "query": {
     "query": "debezium_metrics_MilliSecondsSinceLastEvent"
    }
   },
   {
    "name": "plugin",
    "label": "plugin",
    "query": {
     "query": "debezium_metrics_TotalNumberOfEventsSeen"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Binlog Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total NumberOf EventsSeen",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_TotalNumberOfEventsSeen{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
    }
   ]
  },
  {
   "title": "NumberOf Skipped Events",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_NumberOfErroneousEvents{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
    }
   ]
  },
  {
   "title": "NumberOf Events Filtered",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_NumberOfEventsFiltered{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Connected",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_Connected{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
    }
   ]
  },
  {
   "title": "NumberOf Committed Transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_NumberOfCommittedTransactions{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
    }
   ]
  },
  {
   "title": "NumberOf Not Disconnects",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_NumberOfDisconnects{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\r\n"
    }
   ]
  },
  {
   "title": "Queue Total Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_QueueTotalCapacity{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Queue Remaining Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_QueueRemainingCapacity{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
    }
   ]
  },
  {
   "title": "MilliSeconds Behind Source",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_MilliSecondsBehindSource{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
    }
   ]
  },
  {
   "title": "NumberOf Disconnects",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_NumberOfDisconnects{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Snapshot Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Tablecount",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_TotalTableCount{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}"
    }
   ]
  },
  {
   "title": "Remaining Tales",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_RemainingTableCount{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}"
    }
   ]
  },
  {
   "title": "Snapshot Running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_SnapshotRunning{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}"
    }
   ]
  },
  {
   "title": "Snapshot Aborted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_SnapshotAborted{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Snapshot Completed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_SnapshotCompleted{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}"
    }
   ]
  },
  {
   "title": "MilliSeconds Since LastEvent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_MilliSecondsSinceLastEvent{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\r\n"
    }
   ]
  },
  {
   "title": "Snapshot Duration",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_SnapshotDurationInSeconds{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
    }
   ]
  },
  {
   "title": "NumberOf Events Filtered",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_NumberOfEventsFiltered{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Queue Total Capacity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_QueueTotalCapacity{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Queue Remaining Capacity",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_QueueRemainingCapacity{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
    }
   ]
  },
  {
   "title": "NumberOf Erroneous Events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_NumberOfErroneousEvents{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\r\n"
    }
   ]
  },
  {
   "title": "Total NumberOf Events Seen",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "debezium_metrics_TotalNumberOfEventsSeen{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
    }
   ]
  }
 ]
}